services:
  3xui:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        XRAY_REPO: ${XRAY_REPO:-Lagnuty/Xray-core}
        XRAY_VERSION: ${XRAY_VERSION:-v26.7.11-lagnuty.2}
        XRAY_VERSION_LABEL: ${XRAY_VERSION_LABEL:-26.7.11-lagnuty.1}
    container_name: 3xui_app
    # hostname: yourhostname <- optional
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XUI_WEB_PORT: "${XUI_WEB_PORT:-2053}"
      XUI_SUB_PORT: "${XUI_SUB_PORT:-2097}"
      XUI_SUB_ENABLE: "${XUI_SUB_ENABLE:-true}"
      XUI_XRAY_METRICS_PORT: "${XUI_XRAY_METRICS_PORT:-11112}"
      XUI_XRAY_API_PORT: "${XUI_XRAY_API_PORT:-62789}"
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
